// Soulcalibur
// #ID = 3395

achievement(
    title = "Lone Swordsman", points = 5,
    description = "Complete Arcade mode as Mitsurugi [>= Medium] [Default Settings]",
    id = 195840, badge = "217818", published = "2/2/2022 5:07:15 AM", modified = "2/3/2022 12:36:20 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A6382) >
               prev(word(0x3A6382))
)

achievement(
    title = "Heart and Soul Girl", points = 5,
    description = "Complete Arcade mode as Seungmina [>= Medium] [Default Settings]",
    id = 195841, badge = "217810", published = "2/2/2022 5:07:16 AM", modified = "2/3/2022 12:36:17 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A6386) >
               prev(word(0x3A6386))
)

achievement(
    title = "Dream Shadow of Demon Sealer", points = 5,
    description = "Complete Arcade mode as Taki [>= Medium] [Default Settings]",
    id = 195842, badge = "217804", published = "2/2/2022 5:07:16 AM", modified = "2/3/2022 12:36:15 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A638A) >
               prev(word(0x3A638A))
)

achievement(
    title = "Dandy from the South Sea", points = 5,
    description = "Complete Arcade mode as Maxi [>= Medium] [Default Settings]",
    id = 195843, badge = "217803", published = "2/2/2022 5:07:16 AM", modified = "2/3/2022 12:36:15 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A638E) >
               prev(word(0x3A638E))
)

achievement(
    title = "Hell Guardian", points = 5,
    description = "Complete Arcade mode as Voldo [>= Medium] [Default Settings]",
    id = 195844, badge = "217811", published = "2/2/2022 5:07:17 AM", modified = "2/3/2022 12:36:17 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A6392) >
               prev(word(0x3A6392))
)

achievement(
    title = "Second Advent of the Vow", points = 5,
    description = "Complete Arcade mode as Sophitia [>= Medium] [Default Settings]",
    id = 195845, badge = "217831", published = "2/2/2022 5:07:17 AM", modified = "2/3/2022 12:36:24 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A6396) >
               prev(word(0x3A6396))
)

achievement(
    title = "A Soul in Purgatory", points = 5,
    description = "Complete Arcade mode as Siegfried [>= Medium] [Default Settings]",
    id = 195846, badge = "217796", published = "2/2/2022 5:07:17 AM", modified = "2/3/2022 12:36:12 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A639A) >
               prev(word(0x3A639A))
)

achievement(
    title = "The Trembling Earth", points = 5,
    description = "Complete Arcade mode as Rock [>= Medium] [Default Settings]",
    id = 195847, badge = "217850", published = "2/2/2022 5:07:18 AM", modified = "2/3/2022 12:36:31 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A639E) >
               prev(word(0x3A639E))
)

achievement(
    title = "Patriot's Burning Soul", points = 5,
    description = "Complete Arcade mode as Hwang [>= Medium] [Default Settings]",
    id = 195848, badge = "217823", published = "2/2/2022 5:07:18 AM", modified = "2/3/2022 12:36:21 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63A2) >
               prev(word(0x3A63A2))
)

achievement(
    title = "Wreathing Blade of Isolation", points = 5,
    description = "Complete Arcade mode as Ivy [>= Medium] [Default Settings]",
    id = 195849, badge = "217854", published = "2/2/2022 5:07:18 AM", modified = "2/3/2022 12:36:32 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63AA) >
               prev(word(0x3A63AA))
)

achievement(
    title = "Awaken Destiny", points = 5,
    description = "Complete Arcade mode as Kilik [>= Medium] [Default Settings]",
    id = 195850, badge = "217797", published = "2/2/2022 5:07:19 AM", modified = "2/3/2022 12:36:12 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63AE) >
               prev(word(0x3A63AE))
)

achievement(
    title = "Itenerant Flower of the Breeze", points = 5,
    description = "Complete Arcade mode as Xianghua [>= Medium] [Default Settings]",
    id = 195851, badge = "217814", published = "2/2/2022 5:07:19 AM", modified = "2/3/2022 12:36:18 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63B2) >
               prev(word(0x3A63B2))
)

achievement(
    title = "Jasper Scales of Shudder", points = 5,
    description = "Complete Arcade mode as Lizardman [>= Medium] [Default Settings]",
    id = 195852, badge = "217816", published = "2/2/2022 5:07:19 AM", modified = "2/3/2022 12:36:19 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63B6) >
               prev(word(0x3A63B6))
)

achievement(
    title = "Protector of the Poor", points = 5,
    description = "Complete Arcade mode as Yoshimitsu [>= Medium] [Default Settings]",
    id = 195853, badge = "217828", published = "2/2/2022 5:07:20 AM", modified = "2/3/2022 12:36:23 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63BA) >
               prev(word(0x3A63BA))
)

achievement(
    title = "Edge Lord", points = 5,
    description = "Complete Arcade mode as Edge Master [>= Medium] [Default Settings]",
    id = 195854, badge = "217805", published = "2/2/2022 5:07:20 AM", modified = "2/3/2022 12:36:15 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63BE) >
               prev(word(0x3A63BE))
)

achievement(
    title = "Azure Nightmare", points = 5,
    description = "Complete Arcade mode as Nightmare [>= Medium] [Default Settings]",
    id = 195855, badge = "217798", published = "2/2/2022 5:07:20 AM", modified = "2/3/2022 12:36:13 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63C2) >
               prev(word(0x3A63C2))
)

achievement(
    title = "A Soldier of the Heretic", points = 5,
    description = "Complete Arcade mode as Astaroth [>= Medium] [Default Settings]",
    id = 195856, badge = "217795", published = "2/2/2022 5:07:21 AM", modified = "2/3/2022 12:36:12 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63C6) >
               prev(word(0x3A63C6))
)

achievement(
    title = "The Hellfire of Despair", points = 5,
    description = "Complete Arcade mode as Inferno [>= Medium] [Default Settings]",
    id = 195857, badge = "217844", published = "2/2/2022 5:07:21 AM", modified = "2/3/2022 12:36:29 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63CA) >
               prev(word(0x3A63CA))
)

achievement(
    title = "The Immortal Pirate", points = 5,
    description = "Complete Arcade mode [Cervantes] [>= Medium] [Default Settings]",
    id = 195858, badge = "217846", published = "2/2/2022 5:07:21 AM", modified = "2/3/2022 12:36:29 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && word(0x3A63CE) >
               prev(word(0x3A63CE))
)

achievement(
    title = "The Hero in the Warlike Age", points = 5,
    description = "Unlock Hwang Seong-gyeong (Complete Arcade mode with 1 character)",
    id = 195398, badge = "217845", published = "1/29/2022 8:21:50 PM", modified = "2/13/2022 3:58:38 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 1 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 0
)

achievement(
    title = "The First Mechanized Ninja", points = 5,
    description = "Unlock Yoshimitsu (Complete Arcade mode with 2 characters)",
    id = 195399, badge = "217843", published = "1/29/2022 8:21:50 PM", modified = "2/13/2022 3:58:38 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 2 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 1
)

achievement(
    title = "Jade-Scaled Terror", points = 5,
    description = "Unlock Lizardman (Complete Arcade mode with 3 characters)",
    id = 195400, badge = "217815", published = "1/29/2022 8:21:51 PM", modified = "2/13/2022 3:58:38 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 3 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 2
)

achievement(
    title = "Bamboo Raftin'", points = 5,
    description = "Unlock the Water Labyrinth Arena (Complete Arcade mode with 4 characters)",
    id = 195401, badge = "217898", published = "1/29/2022 8:21:51 PM", modified = "2/13/2022 3:58:39 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 4 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 3
)

achievement(
    title = "Innocent Darkside", points = 5,
    description = "Unlock Siegfried (Complete Arcade mode with 5 characters)",
    id = 195402, badge = "217813", published = "1/29/2022 8:21:51 PM", modified = "2/13/2022 3:58:39 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 5 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 4
)

achievement(
    title = "Venice to See You", points = 5,
    description = "Unlock the City of Water Arena (Complete Arcade mode with 6 characters)",
    id = 195403, badge = "217896", published = "1/29/2022 8:21:52 PM", modified = "2/13/2022 3:58:39 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 6 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 5
)

achievement(
    title = "Reckless Commando", points = 5,
    description = "Unlock Rock (Complete Arcade mode with 7 characters)",
    id = 195404, badge = "217830", published = "1/29/2022 8:21:52 PM", modified = "2/13/2022 3:58:40 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 7 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 6
)

achievement(
    title = "Ready for a Fight", points = 5,
    description = "Unlock the Colloseum Arena (Complete Arcade mode with 8 characters)",
    id = 195405, badge = "217897", published = "1/29/2022 8:21:52 PM", modified = "2/13/2022 3:58:40 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 8 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 7
)

achievement(
    title = "The Master's Daughter", points = 5,
    description = "Unlock Seung Mina (Complete Arcade mode with 9 characters)",
    id = 195406, badge = "217848", published = "1/29/2022 8:21:53 PM", modified = "2/13/2022 3:58:40 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 9 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 8
)

achievement(
    title = "Cervantes de Leon", points = 10,
    description = "Unlock Cervantes (Complete Arcade mode with 10 characters)",
    id = 195407, badge = "217856", published = "1/29/2022 8:21:53 PM", modified = "2/13/2022 3:58:41 AM",
    trigger = dword(0x2C8144) == 7 && dword(0x2C817C) == 19 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) +
               word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) +
               word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) +
               word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) +
               word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 10 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A638A)) / prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) +
               prev(word(0x3A6392)) / prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) +
               prev(word(0x3A63AA)) / prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) +
               prev(word(0x3A63B2)) / prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63BA)) / prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) +
               prev(word(0x3A639A)) / prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 9
)

achievement(
    title = "The Master of Blades", points = 10,
    description = "Unlock Edge Master (Complete Arcade mode with 17 characters)",
    id = 195408, badge = "217847", published = "1/29/2022 8:21:53 PM", modified = "3/14/2022 4:45:02 AM",
    trigger = dword(0x2C8144) == 7 && byte(0x2CAC68) == 1 && (word(0x3A6382) / word(0x3A6382) + word(0x3A638A) /
               word(0x3A638A) + word(0x3A638E) / word(0x3A638E) + word(0x3A6392) / word(0x3A6392) + word(0x3A6396) /
               word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) + word(0x3A63B2) /
               word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) + word(0x3A63A2) /
               word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63B6) / word(0x3A63B6) + word(0x3A639A) /
               word(0x3A639A) + word(0x3A639E) / word(0x3A639E) + word(0x3A6386) / word(0x3A6386) + word(0x3A63CE) /
               word(0x3A63CE) + 0) == 17 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) + prev(word(0x3A638A)) /
               prev(word(0x3A638A)) + prev(word(0x3A638E)) / prev(word(0x3A638E)) + prev(word(0x3A6392)) /
               prev(word(0x3A6392)) + prev(word(0x3A6396)) / prev(word(0x3A6396)) + prev(word(0x3A63AA)) /
               prev(word(0x3A63AA)) + prev(word(0x3A63AE)) / prev(word(0x3A63AE)) + prev(word(0x3A63B2)) /
               prev(word(0x3A63B2)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) + prev(word(0x3A63C6)) /
               prev(word(0x3A63C6)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) + prev(word(0x3A63BA)) /
               prev(word(0x3A63BA)) + prev(word(0x3A63B6)) / prev(word(0x3A63B6)) + prev(word(0x3A639A)) /
               prev(word(0x3A639A)) + prev(word(0x3A639E)) / prev(word(0x3A639E)) + prev(word(0x3A6386)) /
               prev(word(0x3A6386)) + prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 16
)

achievement(
    title = "Sword of Salvation", points = 25,
    description = "Unlock Inferno (Unlock Edge Master and clear Arcade with Xianghua in her 3rd costume)",
    id = 195409, badge = "217837", published = "1/29/2022 8:21:54 PM", modified = "5/22/2022 4:08:14 AM",
    trigger = word(0x3A63C8) == 65535 && word(0x3A63B2) > prev(word(0x3A63B2)) && bit4(0x3A63E8) > prev(bit4(0x3A63E8)) && 
              (word(0x3A6382) / word(0x3A6382) + word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) +
               word(0x3A6392) / word(0x3A6392) + word(0x3A6396) / word(0x3A6396) + word(0x3A63AA) / word(0x3A63AA) +
               word(0x3A63AE) / word(0x3A63AE) + word(0x3A63B2) / word(0x3A63B2) + word(0x3A63C2) / word(0x3A63C2) +
               word(0x3A63C6) / word(0x3A63C6) + word(0x3A63A2) / word(0x3A63A2) + word(0x3A63BA) / word(0x3A63BA) +
               word(0x3A63B6) / word(0x3A63B6) + word(0x3A639A) / word(0x3A639A) + word(0x3A639E) / word(0x3A639E) +
               word(0x3A6386) / word(0x3A6386) + word(0x3A63CE) / word(0x3A63CE) + 0) == 17 && dword(0x2C8144) == 7 && 
              dword(0x2C817C) == 19 && byte(0x2CAC68) == 1
)

achievement(
    title = "Adept Fighter", points = 5,
    description = "Complete Arcade mode with every character [Default Settings]",
    id = 195859, badge = "217866", published = "2/2/2022 5:07:22 AM", modified = "2/3/2022 1:16:06 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 1 && dword(0x2C8144) == 7 && (word(0x3A6382) / word(0x3A6382) +
               word(0x3A6386) / word(0x3A6386) + word(0x3A638A) / word(0x3A638A) + word(0x3A638E) / word(0x3A638E) +
               word(0x3A6392) / word(0x3A6392) + word(0x3A6396) / word(0x3A6396) + word(0x3A639A) / word(0x3A639A) +
               word(0x3A639E) / word(0x3A639E) + word(0x3A63A2) / word(0x3A63A2) + word(0x3A63A6) / word(0x3A63A6) +
               word(0x3A63AA) / word(0x3A63AA) + word(0x3A63AE) / word(0x3A63AE) + word(0x3A63B2) / word(0x3A63B2) +
               word(0x3A63B6) / word(0x3A63B6) + word(0x3A63BA) / word(0x3A63BA) + word(0x3A63BE) / word(0x3A63BE) +
               word(0x3A63C2) / word(0x3A63C2) + word(0x3A63C6) / word(0x3A63C6) + word(0x3A63CA) / word(0x3A63CA) +
               word(0x3A63CE) / word(0x3A63CE) + 0) == 19 && (prev(word(0x3A6382)) / prev(word(0x3A6382)) +
               prev(word(0x3A6386)) / prev(word(0x3A6386)) + prev(word(0x3A638A)) / prev(word(0x3A638A)) +
               prev(word(0x3A638E)) / prev(word(0x3A638E)) + prev(word(0x3A6392)) / prev(word(0x3A6392)) +
               prev(word(0x3A6396)) / prev(word(0x3A6396)) + prev(word(0x3A639A)) / prev(word(0x3A639A)) +
               prev(word(0x3A639E)) / prev(word(0x3A639E)) + prev(word(0x3A63A2)) / prev(word(0x3A63A2)) +
               prev(word(0x3A63A6)) / prev(word(0x3A63A6)) + prev(word(0x3A63AA)) / prev(word(0x3A63AA)) +
               prev(word(0x3A63AE)) / prev(word(0x3A63AE)) + prev(word(0x3A63B2)) / prev(word(0x3A63B2)) +
               prev(word(0x3A63B6)) / prev(word(0x3A63B6)) + prev(word(0x3A63BA)) / prev(word(0x3A63BA)) +
               prev(word(0x3A63BE)) / prev(word(0x3A63BE)) + prev(word(0x3A63C2)) / prev(word(0x3A63C2)) +
               prev(word(0x3A63C6)) / prev(word(0x3A63C6)) + prev(word(0x3A63CA)) / prev(word(0x3A63CA)) +
               prev(word(0x3A63CE)) / prev(word(0x3A63CE)) + 0) == 18
)

achievement(
    title = "Respected", points = 5,
    description = "Complete Arcade mode [>= Hard] [Any Character] [Default Settings]",
    id = 195860, badge = "217867", published = "2/2/2022 5:07:22 AM", modified = "2/3/2022 1:19:45 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 2 && dword(0x2C8144) == 7 &&
              ((word(0x3A6382) > prev(word(0x3A6382))) ||
               (word(0x3A6386) > prev(word(0x3A6386))) ||
               (word(0x3A638A) > prev(word(0x3A638A))) ||
               (word(0x3A638E) > prev(word(0x3A638E))) ||
               (word(0x3A6392) > prev(word(0x3A6392))) ||
               (word(0x3A6396) > prev(word(0x3A6396))) ||
               (word(0x3A639A) > prev(word(0x3A639A))) ||
               (word(0x3A639E) > prev(word(0x3A639E))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE))))
)

achievement(
    title = "The Chosen One", points = 5,
    description = "Complete Arcade mode [>= Very Hard] [Any Character] [Default Settings]",
    id = 195861, badge = "217870", published = "2/2/2022 5:07:22 AM", modified = "2/3/2022 1:26:46 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 3 && dword(0x2C8144) == 7 &&
              ((word(0x3A6382) > prev(word(0x3A6382))) ||
               (word(0x3A6386) > prev(word(0x3A6386))) ||
               (word(0x3A638A) > prev(word(0x3A638A))) ||
               (word(0x3A638E) > prev(word(0x3A638E))) ||
               (word(0x3A6392) > prev(word(0x3A6392))) ||
               (word(0x3A6396) > prev(word(0x3A6396))) ||
               (word(0x3A639A) > prev(word(0x3A639A))) ||
               (word(0x3A639E) > prev(word(0x3A639E))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE))))
)

achievement(
    title = "The Ruler", points = 5,
    description = "Complete Arcade mode [Ultra Hard] [Any Character] [Default Settings]",
    id = 195862, badge = "217869", published = "2/2/2022 5:07:23 AM", modified = "2/3/2022 1:26:19 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) == 4 && dword(0x2C8144) == 7 &&
              ((word(0x3A6382) > prev(word(0x3A6382))) ||
               (word(0x3A6386) > prev(word(0x3A6386))) ||
               (word(0x3A638A) > prev(word(0x3A638A))) ||
               (word(0x3A638E) > prev(word(0x3A638E))) ||
               (word(0x3A6392) > prev(word(0x3A6392))) ||
               (word(0x3A6396) > prev(word(0x3A6396))) ||
               (word(0x3A639A) > prev(word(0x3A639A))) ||
               (word(0x3A639E) > prev(word(0x3A639E))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE))))
)

achievement(
    title = "Mental Breakdown", points = 50,
    description = "Complete Arcade mode [Ultra Hard] [Any Character] [No Losses] [Default Settings]",
    id = 195863, badge = "217868", published = "2/2/2022 5:07:23 AM", modified = "2/3/2022 1:26:06 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) == 4 && dword(0x2C8144) == 7 && never(prev(byte(0x2CAC68)) != 1) &&
              ((word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) != 0))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) != 0))))
)

achievement(
    title = "Dashing Victory", points = 10,
    description = "Complete Arcade mode [>= Hard] [Any Character] [No Continues] [Default Settings]",
    id = 195864, badge = "217887", published = "2/2/2022 5:07:23 AM", modified = "2/3/2022 1:32:26 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 2 && dword(0x2C8144) == 7 && never(prev(byte(0x2CAC68)) != 1) &&
              ((word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))))
)

achievement(
    title = "Proud Victory", points = 10,
    description = "Complete Arcade mode [>= Very Hard] [Any Character] [No Continues] [Default Settings]",
    id = 195865, badge = "217888", published = "2/2/2022 5:07:24 AM", modified = "2/3/2022 1:32:44 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) >= 3 && dword(0x2C8144) == 7 && never(prev(byte(0x2CAC68)) != 1) &&
              ((word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))))
)

achievement(
    title = "Glorious Victory", points = 25,
    description = "Complete Arcade mode [Ultra Hard] [Any Character] [No Continues] [Default Settings]",
    id = 195866, badge = "217889", published = "2/2/2022 5:07:24 AM", modified = "2/13/2022 2:47:10 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 1 && byte(0x2CAD50) == 4 && dword(0x2C8144) == 7 && never(prev(byte(0x2CAC68)) != 1) &&
              ((word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6382) > prev(word(0x3A6382)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6386) > prev(word(0x3A6386)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A638A) > prev(word(0x3A638A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A638E) > prev(word(0x3A638E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6392) > prev(word(0x3A6392)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A6396) > prev(word(0x3A6396)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A639A) > prev(word(0x3A639A)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A639E) > prev(word(0x3A639E)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63A2) > prev(word(0x3A63A2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63A6) > prev(word(0x3A63A6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63AA) > prev(word(0x3A63AA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63AE) > prev(word(0x3A63AE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63B2) > prev(word(0x3A63B2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63B6) > prev(word(0x3A63B6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63BA) > prev(word(0x3A63BA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63BE) > prev(word(0x3A63BE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63C2) > prev(word(0x3A63C2)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63C6) > prev(word(0x3A63C6)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63CA) > prev(word(0x3A63CA)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 0 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2CA1E0) == 2))) ||
               (word(0x3A63CE) > prev(word(0x3A63CE)) && once(byte(0x2BFA58) == 1 && dword(0x2C8144) == 0 &&
                 word(0x2CAC9E) == 1 && prev(word(0x2CAC9E)) == 0 && never(dword(0x2C1B00) == 2))))
)

achievement(
    title = "Forceful Exit", points = 25,
    description = "Complete Arcade mode with every round being either perfect or ring-out [>= Medium][Any Character] [No Continues] [Default Settings]",
    id = 195867, badge = "217890", published = "2/2/2022 5:07:24 AM", modified = "2/16/2022 9:36:42 PM",
    trigger = byte(0x2CAD50) >= 1 && byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && 
              byte(0x2CAD60) == 0 && never(byte(0x2CAC68) != 1) && once(byte(0x2CAC68) == 1 && prev(byte(0x2CAC68)) ==
               0) &&
              ((never((word(0x2C1B9E) != 17263 && byte(0x2BFA58) == 0 && dword(0x2CA1EC) == 1)) && 
                never((dword(0x2CA1E0) == 2 && byte(0x2BFA58) == 0)) && trigger_when(tally(16, 
                    (byte(0x2BFA58) == 0 && word(0x2C1B9E) == 17263 && dword(0x2CA1EC) == 1 && prev(dword(0x2CA1EC))
                     == 0), 
                byte(0x2BFA58) == 0 &&
                 dword(0x2CA1EC) == 3 && prev(dword(0x2CA1EC)) == 0))) ||
               (never((word(0x2CA27E) != 17263 && byte(0x2BFA58) == 1 && dword(0x2C1B0C) == 1)) && 
                never((dword(0x2C1B00) == 2 && byte(0x2BFA58) == 1)) && trigger_when(tally(16, 
                    (byte(0x2BFA58) == 1 && word(0x2CA27E) == 17263 && dword(0x2C1B0C) == 1 && prev(dword(0x2C1B0C))
                     == 0), 
                byte(0x2BFA58) == 1 &&
                 dword(0x2C1B0C) == 3 && prev(dword(0x2C1B0C)) == 0))))
)

achievement(
    title = "Proving Grounds", points = 10,
    description = "Mission Mode - Proving Grounds - Complete all nine missions",
    id = 195875, badge = "217829", published = "2/2/2022 4:57:15 PM", modified = "2/14/2022 9:26:00 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3B4) / word(0x2DC3B4) + word(0x2DC3B6) / word(0x2DC3B6) +
               word(0x2DC3B8) / word(0x2DC3B8) + word(0x2DC3BA) / word(0x2DC3BA) + word(0x2DC3BC) / word(0x2DC3BC) +
               word(0x2DC3BE) / word(0x2DC3BE) + word(0x2DC3C0) / word(0x2DC3C0) + word(0x2DC3C2) / word(0x2DC3C2) +
               word(0x2DC3C4) / word(0x2DC3C4) + 0) == 9) && (prev(word(0x2DC3B4)) / prev(word(0x2DC3B4)) +
               prev(word(0x2DC3B6)) / prev(word(0x2DC3B6)) + prev(word(0x2DC3B8)) / prev(word(0x2DC3B8)) +
               prev(word(0x2DC3BA)) / prev(word(0x2DC3BA)) + prev(word(0x2DC3BC)) / prev(word(0x2DC3BC)) +
               prev(word(0x2DC3BE)) / prev(word(0x2DC3BE)) + prev(word(0x2DC3C0)) / prev(word(0x2DC3C0)) +
               prev(word(0x2DC3C2)) / prev(word(0x2DC3C2)) + prev(word(0x2DC3C4)) / prev(word(0x2DC3C4)) + 0) == 8 && 
              bit0(0x2DC1C9) == 1 && bit6(0x2DC1CF) == 1 && bit7(0x2DC1CF) == 1 && high4(0x2DC1D0) == 15 && 
              bit4(0x2DC1D0) == 1 && bit5(0x2DC1D0) == 1 && bit6(0x2DC1D0) == 1
)

achievement(
    title = "The Adrian and the Fortress", points = 10,
    description = "Mission Mode - The Adrian and the Fortress - Complete all four missions",
    id = 195876, badge = "217840", published = "2/2/2022 4:57:22 PM", modified = "2/14/2022 9:26:00 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3AC) / word(0x2DC3AC) + word(0x2DC3AE) / word(0x2DC3AE) +
               word(0x2DC3B0) / word(0x2DC3B0) + word(0x2DC3B2) / word(0x2DC3B2) + 0) == 4) && (prev(word(0x2DC3AC)) /
               prev(word(0x02DC3A)) + prev(word(0x2DC3AE)) / prev(word(0x2DC3AE)) + prev(word(0x2DC3B0)) /
               prev(word(0x2DC3B0)) + prev(word(0x2DC3B2)) / prev(word(0x2DC3B2)) + 0) == 3 && bit7(0x2DC1C8) == 1 && 
              bit2(0x2DC1CF) == 1 && bit3(0x2DC1CF) == 1 && bit4(0x2DC1CF) == 1 && bit5(0x2DC1CF) == 1
)

achievement(
    title = "City of Water", points = 10,
    description = "Mission Mode - City of Water - Complete all four missions",
    id = 195877, badge = "217801", published = "2/2/2022 4:57:27 PM", modified = "2/14/2022 9:26:00 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3A4) / word(0x2DC3A4) + word(0x2DC3A6) / word(0x2DC3A6) +
               word(0x2DC3A8) / word(0x2DC3A8) + word(0x2DC3AA) / word(0x2DC3AA) + 0) == 4) && (prev(word(0x2DC3A4)) /
               prev(word(0x2DC3A4)) + prev(word(0x2DC3A6)) / prev(word(0x2DC3A6)) + prev(word(0x2DC3A8)) /
               prev(word(0x2DC3A8)) + prev(word(0x2DC3AA)) / prev(word(0x2DC3AA)) + 0) == 3 && bit6(0x2DC1C8) == 1 && 
              bit6(0x2DC1CE) == 1 && bit7(0x2DC1CE) == 1 && bit0(0x2DC1CF) == 1 && bit1(0x2DC1CF) == 1
)

achievement(
    title = "Emperor's Garden", points = 10,
    description = "Mission Mode - Emperor's Garden - Complete all four missions",
    id = 195878, badge = "217806", published = "2/2/2022 4:57:32 PM", modified = "2/14/2022 9:26:01 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3F8) / word(0x2DC3F8) + word(0x2DC3FA) / word(0x2DC3FA) +
               word(0x2DC3FC) / word(0x2DC3FC) + word(0x2DC3FE) / word(0x2DC3FE) + 0) == 4) && (prev(word(0x2DC3F8)) /
               prev(word(0x2DC3F8)) + prev(word(0x2DC3FA)) / prev(word(0x2DC3FA)) + prev(word(0x2DC3FC)) /
               prev(word(0x2DC3FC)) + prev(word(0x2DC3FE)) / prev(word(0x2DC3FE)) + 0) == 3 && bit7(0x2DC1C9) == 1 && 
              low4(0x2DC1D4) == 15
)

achievement(
    title = "Harbor of Souls", points = 10,
    description = "Mission Mode - Harbor of Souls - Complete all four missions",
    id = 195879, badge = "217809", published = "2/2/2022 4:57:37 PM", modified = "2/14/2022 9:26:01 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3C6) / word(0x2DC3C6) + word(0x2DC3C8) / word(0x2DC3C8) +
               word(0x2DC3CA) / word(0x2DC3CA) + word(0x2DC3CC) / word(0x2DC3CC) + 0) == 4) && (prev(word(0x2DC3C6)) /
               prev(word(0x2DC3C6)) + prev(word(0x2DC3C8)) / prev(word(0x2DC3C8)) + prev(word(0x2DC3CA)) /
               prev(word(0x2DC3CA)) + prev(word(0x2DC3CC)) / prev(word(0x2DC3CC)) + 0) == 3 && bit1(0x2DC1C9) == 1 && 
              bit7(0x2DC1D0) == 1 && bit0(0x2DC1D1) == 1 && bit1(0x2DC1D1) == 1 && bit2(0x2DC1D1) == 1
)

achievement(
    title = "The Colosseum", points = 10,
    description = "Mission Mode - The Colosseum - Complete all four missions",
    id = 195880, badge = "217842", published = "2/2/2022 4:57:41 PM", modified = "5/22/2022 4:02:57 AM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC39C) / word(0x2DC39C) + word(0x2DC39E) / word(0x2DC39E) +
               word(0x2DC3A0) / word(0x2DC3A0) + word(0x2DC3A2) / word(0x2DC3A2) + 0) == 4) && (prev(word(0x2DC39C)) /
               prev(word(0x2DC39C)) + prev(word(0x2DC39E)) / prev(word(0x2DC39E)) + prev(word(0x2DC3A0)) /
               prev(word(0x2DC3A0)) + prev(word(0x2DC3A2)) / prev(word(0x2DC3A2)) + 0) == 3 && bit5(0x2DC1C8) == 1 && 
              bit2(0x2DC1CE) == 1 && bit3(0x2DC1CE) == 1 && bit4(0x2DC1CE) == 1 && bit5(0x2DC1CE) == 1
)

achievement(
    title = "Valentine Mansion", points = 10,
    description = "Mission Mode - Valentine Mansion - Complete all four missions",
    id = 195881, badge = "217852", published = "2/2/2022 4:57:42 PM", modified = "2/14/2022 9:26:02 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC37C) / word(0x2DC37C) + word(0x2DC37E) / word(0x2DC37E) +
               word(0x2DC380) / word(0x2DC380) + word(0x2DC382) / word(0x2DC382) + 0) == 4) && (prev(word(0x2DC37C)) /
               prev(word(0x2DC37C)) + prev(word(0x2DC37E)) / prev(word(0x2DC37E)) + prev(word(0x2DC380)) /
               prev(word(0x2DC380)) + prev(word(0x2DC382)) / prev(word(0x2DC382)) + 0) == 3 && bit1(0x2DC1C8) == 1 && 
              bit2(0x2DC1CC) == 1 && bit3(0x2DC1CC) == 1 && bit4(0x2DC1CC) == 1 && bit5(0x2DC1CC) == 1
)

achievement(
    title = "Ostreinsburg Castle", points = 10,
    description = "Mission Mode - Ostreinsburg Castle - Complete all four missions",
    id = 195882, badge = "217821", published = "2/2/2022 4:57:42 PM", modified = "2/14/2022 9:26:02 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC384) / word(0x2DC384) + word(0x2DC386) / word(0x2DC386) +
               word(0x2DC388) / word(0x2DC388) + word(0x2DC38A) / word(0x2DC38A) + 0) == 4) && (prev(word(0x2DC384)) /
               prev(word(0x2DC384)) + prev(word(0x2DC386)) / prev(word(0x2DC386)) + prev(word(0x2DC388)) /
               prev(word(0x2DC388)) + prev(word(0x2DC38A)) / prev(word(0x2DC38A)) + 0) == 3 && bit2(0x2DC1C8) == 1 && 
              bit6(0x2DC1CC) == 1 && bit7(0x2DC1CC) == 1 && bit0(0x2DC1CD) == 1 && bit1(0x2DC1CD) == 1
)

achievement(
    title = "Money Pit", points = 10,
    description = "Mission Mode - Money Pit - Complete all four missions",
    id = 195883, badge = "217820", published = "2/2/2022 4:57:42 PM", modified = "2/14/2022 9:26:02 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC38C) / word(0x2DC38C) + word(0x2DC38E) / word(0x2DC38E) +
               word(0x2DC390) / word(0x2DC390) + word(0x2DC392) / word(0x2DC392) + 0) == 4) && (prev(word(0x2DC38C)) /
               prev(word(0x2DC38C)) + prev(word(0x2DC38E)) / prev(word(0x2DC38E)) + prev(word(0x2DC390)) /
               prev(word(0x2DC390)) + prev(word(0x2DC392)) / prev(word(0x2DC392)) + 0) == 3 && bit3(0x2DC1C8) == 1 && 
              bit2(0x2DC1CD) == 1 && bit3(0x2DC1CD) == 1 && bit4(0x2DC1CD) == 1 && bit5(0x2DC1CD) == 1
)

achievement(
    title = "Shrine of Eurydice", points = 10,
    description = "Mission Mode - Shrine of Eurydice - Complete all four missions",
    id = 195884, badge = "217833", published = "2/2/2022 4:57:43 PM", modified = "2/14/2022 9:26:03 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC394) / word(0x2DC394) + word(0x2DC396) / word(0x2DC396) +
               word(0x2DC398) / word(0x2DC398) + word(0x2DC39A) / word(0x2DC39A) + 0) == 4) && (prev(word(0x2DC394)) /
               prev(word(0x2DC394)) + prev(word(0x2DC396)) / prev(word(0x2DC396)) + prev(word(0x2DC398)) /
               prev(word(0x2DC398)) + prev(word(0x2DC39A)) / prev(word(0x2DC39A)) + 0) == 3 && bit4(0x2DC1C8) == 1 && 
              bit6(0x2DC1CD) == 1 && bit7(0x2DC1CD) == 1 && bit0(0x2DC1CE) == 1 && bit1(0x2DC1CE) == 1
)

achievement(
    title = "Palgaea Shrine", points = 10,
    description = "Mission Mode - Palgaea Shrine - Complete all four missions",
    id = 195885, badge = "217822", published = "2/2/2022 4:57:43 PM", modified = "2/14/2022 9:26:03 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3CE) / word(0x2DC3CE) + word(0x2DC3D0) / word(0x2DC3D0) +
               word(0x2DC3D2) / word(0x2DC3D2) + word(0x2DC3D4) / word(0x2DC3D4) + 0) == 4) && (prev(word(0x2DC3CE)) /
               prev(word(0x2DC3CE)) + prev(word(0x2DC3D0)) / prev(word(0x2DC3D0)) + prev(word(0x2DC3D2)) /
               prev(word(0x2DC3D2)) + prev(word(0x2DC3D4)) / prev(word(0x2DC3D4)) + 0) == 3 && bit2(0x2DC1C9) == 1 && 
              bit3(0x2DC1D1) == 1 && bit4(0x2DC1D1) == 1 && bit5(0x2DC1D1) == 1 && bit6(0x2DC1D1) == 1
)

achievement(
    title = "Kunpaetku Shrine", points = 10,
    description = "Mission Mode - Kunpaetku Shrine - Complete all four missions",
    id = 195886, badge = "217817", published = "2/2/2022 4:57:43 PM", modified = "2/14/2022 9:26:03 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3D6) / word(0x2DC3D6) + word(0x2DC3D8) / word(0x2DC3D8) +
               word(0x2DC3DA) / word(0x2DC3DA) + word(0x2DC3DC) / word(0x2DC3DC) + 0) == 4) && (prev(word(0x2DC3D6)) /
               prev(word(0x2DC3D6)) + prev(word(0x2DC3D8)) / prev(word(0x2DC3D8)) + prev(word(0x2DC3DA)) /
               prev(word(0x2DC3DA)) + prev(word(0x2DC3DC)) / prev(word(0x2DC3DC)) + 0) == 3 && bit3(0x2DC1C9) == 1 && 
              bit7(0x2DC1D1) == 1 && bit0(0x2DC1D2) == 1 && bit1(0x2DC1D2) == 1 && bit2(0x2DC1D2) == 1
)

achievement(
    title = "Maze of the Dead", points = 10,
    description = "Mission Mode - Maze of the Dead - Complete all four missions",
    id = 195887, badge = "217819", published = "2/2/2022 4:57:44 PM", modified = "2/14/2022 9:26:04 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3DE) / word(0x2DC3DE) + word(0x2DC3E0) / word(0x2DC3E0) +
               word(0x2DC3E2) / word(0x2DC3E2) + word(0x2DC3E4) / word(0x2DC3E4) + 0) == 4) && (prev(word(0x2DC3DE)) /
               prev(word(0x2DC3DE)) + prev(word(0x2DC3E0)) / prev(word(0x2DC3E0)) + prev(word(0x2DC3E2)) /
               prev(word(0x2DC3E2)) + prev(word(0x2DC3E4)) / prev(word(0x2DC3E4)) + 0) == 3 && bit4(0x2DC1C9) == 1 && 
              bit3(0x2DC1D2) == 1 && bit4(0x2DC1D2) == 1 && bit5(0x2DC1D2) == 1 && bit6(0x2DC1D2) == 1
)

achievement(
    title = "Silk Road Ruins", points = 10,
    description = "Mission Mode - Silk Road Ruins - Complete all four missions",
    id = 195888, badge = "217834", published = "2/2/2022 4:57:44 PM", modified = "2/14/2022 9:26:04 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3E6) / word(0x2DC3E6) + word(0x2DC3E8) / word(0x2DC3E8) +
               word(0x2DC3EA) / word(0x2DC3EA) + word(0x2DC3EC) / word(0x2DC3EC) + 0) == 4) && (prev(word(0x2DC3E6)) /
               prev(word(0x2DC3E6)) + prev(word(0x2DC3E8)) / prev(word(0x2DC3E8)) + prev(word(0x2DC3EA)) /
               prev(word(0x2DC3EA)) + prev(word(0x2DC3EC)) / prev(word(0x2DC3EC)) + 0) == 3 && bit5(0x2DC1C9) == 1 && 
              bit7(0x2DC1D2) == 1 && bit0(0x2DC1D3) == 1 && bit1(0x2DC1D3) == 1 && bit2(0x2DC1D3) == 1
)

achievement(
    title = "Takamatsu Castle", points = 10,
    description = "Mission Mode - Takamatsu Castle - Complete all four missions",
    id = 195889, badge = "217839", published = "2/2/2022 4:57:44 PM", modified = "2/14/2022 9:26:04 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC400) / word(0x2DC400) + word(0x2DC402) / word(0x2DC402) +
               word(0x2DC404) / word(0x2DC404) + word(0x2DC406) / word(0x2DC406) + 0) == 4) && (prev(word(0x2DC400)) /
               prev(word(0x2DC400)) + prev(word(0x2DC402)) / prev(word(0x2DC402)) + prev(word(0x2DC404)) /
               prev(word(0x2DC404)) + prev(word(0x2DC406)) / prev(word(0x2DC406)) + 0) == 3 && bit2(0x2DC1CA) == 1 && 
              high4(0x2DC1D4) == 15
)

achievement(
    title = "Hoko Temple", points = 10,
    description = "Mission Mode - Hoko Temple - Complete all four missions",
    id = 195890, badge = "217812", published = "2/2/2022 4:57:45 PM", modified = "2/14/2022 9:26:05 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC408) / word(0x2DC408) + word(0x2DC40A) / word(0x2DC40A) +
               word(0x2DC40C) / word(0x2DC40C) + word(0x2DC40E) / word(0x2DC40E) + 0) == 4) && (prev(word(0x2DC408)) /
               prev(word(0x2DC408)) + prev(word(0x2DC40A)) / prev(word(0x2DC40A)) + prev(word(0x2DC40C)) /
               prev(word(0x2DC40C)) + prev(word(0x2DC40E)) / prev(word(0x2DC40E)) + 0) == 3 && bit1(0x2DC1CA) == 1 && 
              low4(0x2DC1D5) == 15
)

achievement(
    title = "Water Labyrinth", points = 10,
    description = "Mission Mode - Water Labyrinth - Complete all four missions",
    id = 195891, badge = "217853", published = "2/2/2022 4:57:45 PM", modified = "2/14/2022 9:26:05 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC410) / word(0x2DC410) + word(0x2DC412) / word(0x2DC412) +
               word(0x2DC414) / word(0x2DC414) + word(0x2DC416) / word(0x2DC416) + 0) == 4) && (prev(word(0x2DC410)) /
               prev(word(0x2DC410)) + prev(word(0x2DC412)) / prev(word(0x2DC412)) + prev(word(0x2DC414)) /
               prev(word(0x2DC414)) + prev(word(0x2DC416)) / prev(word(0x2DC416)) + 0) == 3 && bit0(0x2DC1CA) == 1 && 
              high4(0x2DC1D5) == 15
)

achievement(
    title = "Chaos", points = 10,
    description = "Mission Mode - Chaos - Complete both missions",
    id = 195892, badge = "217800", published = "2/2/2022 4:57:48 PM", modified = "2/14/2022 9:26:05 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC418) / word(0x2DC418) + word(0x2DC41A) / word(0x2DC41A) + 0) ==
               2) && (prev(word(0x2DC418)) / prev(word(0x2DC418)) + prev(word(0x2DC41A)) / prev(word(0x2DC41A)) + 0) ==
               1 && bit3(0x2DC1CA) == 1 && bit0(0x2DC1D6) == 1 && bit1(0x2DC1D6) == 1
)

achievement(
    title = "Secret Dojo", points = 10,
    description = "Mission Mode - Secret Dojo - Complete all five missions",
    id = 195893, badge = "217832", published = "2/2/2022 4:57:51 PM", modified = "2/14/2022 9:26:06 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC3EE) / word(0x2DC3EE) + word(0x2DC3F0) / word(0x2DC3F0) +
               word(0x2DC3F2) / word(0x2DC3F2) + word(0x2DC3F4) / word(0x2DC3F4) + word(0x2DC3F6) / word(0x2DC3F6) + 0)
               == 5) && (prev(word(0x2DC3EE)) / prev(word(0x2DC3EE)) + prev(word(0x2DC3F0)) / prev(word(0x2DC3F0)) +
               prev(word(0x2DC3F2)) / prev(word(0x2DC3F2)) + prev(word(0x2DC3F4)) / prev(word(0x2DC3F4)) +
               prev(word(0x2DC3F6)) / prev(word(0x2DC3F6)) + 0) == 4 && bit6(0x2DC1C9) == 1 && bit3(0x2DC1D3) == 1 && 
              high4(0x2DC1D3) == 15
)

achievement(
    title = "Pits and Swamps", points = 5,
    description = "Mission Mode - The Pit and The Swamp - Complete both missions",
    id = 195894, badge = "217824", published = "2/2/2022 4:57:51 PM", modified = "2/14/2022 9:26:06 PM",
    trigger = byte(0x2CAC68) == 8 && measured((word(0x2DC378) / word(0x2DC378) + word(0x2DC37A) / word(0x2DC37A) + 0) ==
               2) && (prev(word(0x2DC378)) / prev(word(0x2DC378)) + prev(word(0x2DC37A)) / prev(word(0x2DC37A)) + 0) ==
               1 && bit0(0x2DC1C8) == 1 && bit0(0x2DC1CC) == 1 && bit1(0x2DC1CC) == 1
)

achievement(
    title = "The Tale Begins", points = 5,
    description = "Purchase all 12 cards of The Tale Begins: Prologue",
    id = 195410, badge = "217849", published = "1/29/2022 9:08:58 PM", modified = "2/13/2022 6:42:36 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bitcount(0x2DC18C) + bit0(0x2DC18D) +
               bit1(0x2DC18D) + bit2(0x2DC18D) + bit3(0x2DC18D)) == 12) && (prev(bitcount(0x2DC18C)) +
               prev(bit0(0x2DC18D)) + prev(bit1(0x2DC18D)) + prev(bit2(0x2DC18D)) + prev(bit3(0x2DC18D))) == 11
)

achievement(
    title = "Souls Guided by Destiny", points = 5,
    description = "Purchase all 20 cards of Souls Guided by Destiny: CG Portraits",
    id = 195411, badge = "217835", published = "1/29/2022 9:09:03 PM", modified = "2/13/2022 6:42:37 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bitcount(0x2DC18F) + bitcount(0x2DC18E) +
               bit4(0x2DC18D) + bit5(0x2DC18D) + bit6(0x2DC18D) + bit7(0x2DC18D)) == 20) && (prev(bitcount(0x2DC18F)) +
               prev(bitcount(0x2DC18E)) + prev(bit4(0x2DC18D)) + prev(bit5(0x2DC18D)) + prev(bit6(0x2DC18D)) +
               prev(bit7(0x2DC18D))) == 19
)

achievement(
    title = "Souls Guided by Destiny 2", points = 5,
    description = "Purchase all 18 cards of Souls Guided by Destiny 2: CG Portraits",
    id = 195412, badge = "217836", published = "1/29/2022 9:09:06 PM", modified = "2/13/2022 6:42:37 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bitcount(0x2DC190) + bitcount(0x2DC191) +
               bit0(0x2DC192) + bit1(0x2DC192)) == 18) && (prev(bitcount(0x2DC190)) + prev(bitcount(0x2DC191)) +
               prev(bit0(0x2DC192)) + prev(bit1(0x2DC192))) == 17
)

achievement(
    title = "Symbols", points = 5,
    description = "Purchase all 18 cards of Symbols: Special CG",
    id = 195413, badge = "217838", published = "1/29/2022 9:09:10 PM", modified = "2/13/2022 6:42:37 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bitcount(0x2DC192) + bitcount(0x2DC193) +
               bit0(0x2DC194) + bit1(0x2DC194) + bit2(0x2DC194) + bit3(0x2DC194) - bit0(0x2DC192) - bit1(0x2DC192)) ==
               18) && (prev(bitcount(0x2DC192)) + prev(bitcount(0x2DC193)) + prev(bit0(0x2DC194)) + prev(bit1(0x2DC194))
               + prev(bit2(0x2DC194)) + prev(bit3(0x2DC194)) - prev(bit0(0x2DC192)) - prev(bit1(0x2DC192))) == 17
)

achievement(
    title = "The Chosen Ones", points = 5,
    description = "Purchase all 22 cards of The Chosen Ones: CG Characters",
    id = 195414, badge = "217841", published = "1/29/2022 9:09:15 PM", modified = "2/13/2022 6:42:38 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bit4(0x2DC194) + bit5(0x2DC194) + bit6(0x2DC194)
               + bit7(0x2DC194) + bitcount(0x2DC195) + bitcount(0x2DC196) + bit0(0x2DC197) + bit1(0x2DC197)) == 22) && 
              (prev(bit4(0x2DC194)) + prev(bit5(0x2DC194)) + prev(bit6(0x2DC194)) + prev(bit7(0x2DC194)) +
               prev(bitcount(0x2DC195)) + prev(bitcount(0x2DC196)) + prev(bit0(0x2DC197)) + prev(bit1(0x2DC197))) == 21
)

achievement(
    title = "Portaits of Souls", points = 5,
    description = "Purchase all 19 cards of Portraits of Souls: Character Illustrations",
    id = 195415, badge = "217825", published = "1/29/2022 9:09:19 PM", modified = "2/13/2022 6:42:38 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bitcount(0x2DC197) + bitcount(0x2DC198) +
               bit0(0x2DC199) + bit1(0x2DC199) + bit2(0x2DC199) + bit3(0x2DC199) + bit4(0x2DC199) - bit0(0x2DC197) -
               bit1(0x2DC197)) == 19) && (prev(bitcount(0x2DC197)) + prev(bitcount(0x2DC198)) + prev(bit0(0x2DC199)) +
               prev(bit1(0x2DC199)) + prev(bit2(0x2DC199)) + prev(bit3(0x2DC199)) + prev(bit4(0x2DC199)) -
               prev(bit0(0x2DC197)) - prev(bit1(0x2DC197))) == 18
)

achievement(
    title = "Cursed Souls", points = 5,
    description = "Purchase all 17 cards of Cursed Souls: Monochrome Illustrations",
    id = 195416, badge = "217802", published = "1/29/2022 9:09:22 PM", modified = "2/13/2022 6:42:38 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bit5(0x2DC199) + bit6(0x2DC199) + bit7(0x2DC199)
               + bitcount(0x2DC19A) + bitcount(0x2DC19B) - bit6(0x2DC19B) - bit7(0x2DC19B)) == 17) && 
              (prev(bit5(0x2DC199)) + prev(bit6(0x2DC199)) + prev(bit7(0x2DC199)) + prev(bitcount(0x2DC19A)) +
               prev(bitcount(0x2DC19B)) - prev(bit6(0x2DC19B)) - prev(bit7(0x2DC19B))) == 16
)

achievement(
    title = "Birth of a Soul", points = 10,
    description = "Purchase all 30 cards of Birth of a Soul: Character Concepts",
    id = 195417, badge = "217799", published = "1/29/2022 9:09:25 PM", modified = "2/13/2022 6:42:39 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bit6(0x2DC19B) + bit7(0x2DC19B) +
               bitcount(0x2DC19C) + bitcount(0x2DC19D) + bitcount(0x2DC19E) + bit0(0x2DC19F) + bit1(0x2DC19F) +
               bit2(0x2DC19F) + bit3(0x2DC19F)) == 30) && (prev(bit6(0x2DC19B)) + prev(bit7(0x2DC19B)) +
               prev(bitcount(0x2DC19C)) + prev(bitcount(0x2DC19D)) + prev(bitcount(0x2DC19E)) + prev(bit0(0x2DC19F)) +
               prev(bit1(0x2DC19F)) + prev(bit2(0x2DC19F)) + prev(bit3(0x2DC19F))) == 29
)

achievement(
    title = "Profiles of Warriors", points = 5,
    description = "Purchase all 29 cards of Profiles of Warriors",
    id = 195418, badge = "217826", published = "1/29/2022 9:09:32 PM", modified = "2/13/2022 6:42:39 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bit4(0x2DC19F) + bit5(0x2DC19F) + bit6(0x2DC19F)
               + bit7(0x2DC19F) + bitcount(0x2DC1A0) + bitcount(0x2DC1A1) + bitcount(0x2DC1A2) + bit0(0x2DC1A3)) == 29) && 
              (prev(bit4(0x2DC19F)) + prev(bit5(0x2DC19F)) + prev(bit6(0x2DC19F)) + prev(bit7(0x2DC19F)) +
               prev(bitcount(0x2DC1A0)) + prev(bitcount(0x2DC1A1)) + prev(bitcount(0x2DC1A2)) + prev(bit0(0x2DC1A3))) ==
               28
)

achievement(
    title = "Profiles of Warriors 2", points = 10,
    description = "Purchase all 30 cards of Profiles of Warriors 2",
    id = 195419, badge = "217827", published = "1/29/2022 9:09:35 PM", modified = "2/13/2022 6:42:39 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bitcount(0x2DC1A3) + bitcount(0x2DC1A4) +
               bitcount(0x2DC1A5) + bitcount(0x2DC1A6) - bit0(0x2DC1A3) - bit7(0x2DC1A6)) == 30) && 
              (prev(bitcount(0x2DC1A3)) + prev(bitcount(0x2DC1A4)) + prev(bitcount(0x2DC1A5)) + prev(bitcount(0x2DC1A6))
               - prev(bit0(0x2DC1A3)) - prev(bit7(0x2DC1A6))) == 29
)

achievement(
    title = "End of the Quest", points = 10,
    description = "Purchase all 30 cards of End of the Quest: Endings",
    id = 195420, badge = "217807", published = "1/29/2022 9:09:39 PM", modified = "2/13/2022 6:42:40 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && (bit7(0x2DC1A6) + bitcount(0x2DC1A7) + bitcount(0x2DC1A8)
               + bitcount(0x2DC1A9) + bit0(0x2DC1AA) + bit1(0x2DC1AA) + bit2(0x2DC1AA) + bit3(0x2DC1AA) +
               bit4(0x2DC1AA)) == 30 && (prev(bit7(0x2DC1A6)) + prev(bitcount(0x2DC1A7)) + prev(bitcount(0x2DC1A8)) +
               prev(bitcount(0x2DC1A9)) + prev(bit0(0x2DC1AA)) + prev(bit1(0x2DC1AA)) + prev(bit2(0x2DC1AA)) +
               prev(bit3(0x2DC1AA)) + prev(bit4(0x2DC1AA))) == 29
)

achievement(
    title = "End of the Quest 2", points = 5,
    description = "Purchase all 20 cards of End of the Quest 2: Endings",
    id = 195421, badge = "217808", published = "1/29/2022 9:09:41 PM", modified = "2/13/2022 6:42:40 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bit5(0x2DC1AA) + bit6(0x2DC1AA) + bit7(0x2DC1AA)
               + bitcount(0x2DC1AB) + bitcount(0x2DC1AC) + bit0(0x2DC1AD)) == 20) && (prev(bit5(0x2DC1AA)) +
               prev(bit6(0x2DC1AA)) + prev(bit7(0x2DC1AA)) + prev(bitcount(0x2DC1AB)) + prev(bitcount(0x2DC1AC)) +
               prev(bit0(0x2DC1AD))) == 19
)

achievement(
    title = "The World of Souls and Swords", points = 5,
    description = "Purchase all 16 cards of The World of Souls and Swords: Posters",
    id = 195422, badge = "217851", published = "1/29/2022 9:09:46 PM", modified = "2/13/2022 6:42:40 PM",
    trigger = (byte(0x2CAC68) == 8 || byte(0x2CAC68) == 0) && measured((bitcount(0x2DC1B4) + bitcount(0x2DC1B5) +
               bit0(0x2DC1B6) + bit1(0x2DC1B6) - bit0(0x2DC1B4) - bit1(0x2DC1B4)) == 16) && (prev(bitcount(0x2DC1B4)) +
               prev(bitcount(0x2DC1B5)) + prev(bit0(0x2DC1B6)) + prev(bit1(0x2DC1B6)) - prev(bit0(0x2DC1B4)) -
               prev(bit1(0x2DC1B4))) == 15
)

achievement(
    title = "Nice Job, Nerd", points = 25,
    description = "Purchase all 338 cards in the Gallery",
    id = 195423, badge = "217855", published = "1/29/2022 9:09:48 PM", modified = "2/14/2022 9:19:32 PM",
    trigger = measured((bitcount(0x2DC18C) + bitcount(0x2DC18D) + bitcount(0x2DC18E) + bitcount(0x2DC18F) +
               bitcount(0x2DC190) + bitcount(0x2DC191) + bitcount(0x2DC192) + bitcount(0x2DC193) + bitcount(0x2DC194) +
               bitcount(0x2DC195) + bitcount(0x2DC196) + bitcount(0x2DC197) + bitcount(0x2DC198) + bitcount(0x2DC199) +
               bitcount(0x2DC19A) + bitcount(0x2DC19B) + bitcount(0x2DC19C) + bitcount(0x2DC19D) + bitcount(0x2DC19E) +
               bitcount(0x2DC19F) + bitcount(0x2DC1A0) + bitcount(0x2DC1A1) + bitcount(0x2DC1A2) + bitcount(0x2DC1A3) +
               bitcount(0x2DC1A4) + bitcount(0x2DC1A5) + bitcount(0x2DC1A6) + bitcount(0x2DC1A7) + bitcount(0x2DC1A8) +
               bitcount(0x2DC1A9) + bitcount(0x2DC1AA) + bitcount(0x2DC1AB) + bitcount(0x2DC1AC) + bitcount(0x2DC1AD) +
               bitcount(0x2DC1AE) + bitcount(0x2DC1AF) + bitcount(0x2DC1B0) + bitcount(0x2DC1B1) + bitcount(0x2DC1B2) +
               bitcount(0x2DC1B3) + bitcount(0x2DC1B4) + bitcount(0x2DC1B5) + bit0(0x2DC1B6) + bit1(0x2DC1B6)) == 338) && 
              (prev(bitcount(0x2DC18C)) + prev(bitcount(0x2DC18D)) + prev(bitcount(0x2DC18E)) + prev(bitcount(0x2DC18F))
               + prev(bitcount(0x2DC190)) + prev(bitcount(0x2DC191)) + prev(bitcount(0x2DC192)) +
               prev(bitcount(0x2DC193)) + prev(bitcount(0x2DC194)) + prev(bitcount(0x2DC195)) + prev(bitcount(0x2DC196))
               + prev(bitcount(0x2DC197)) + prev(bitcount(0x2DC198)) + prev(bitcount(0x2DC199)) +
               prev(bitcount(0x2DC19A)) + prev(bitcount(0x2DC19B)) + prev(bitcount(0x2DC19C)) + prev(bitcount(0x2DC19D))
               + prev(bitcount(0x2DC19E)) + prev(bitcount(0x2DC19F)) + prev(bitcount(0x2DC1A0)) +
               prev(bitcount(0x2DC1A1)) + prev(bitcount(0x2DC1A2)) + prev(bitcount(0x2DC1A3)) + prev(bitcount(0x2DC1A4))
               + prev(bitcount(0x2DC1A5)) + prev(bitcount(0x2DC1A6)) + prev(bitcount(0x2DC1A7)) +
               prev(bitcount(0x2DC1A8)) + prev(bitcount(0x2DC1A9)) + prev(bitcount(0x2DC1AA)) + prev(bitcount(0x2DC1AB))
               + prev(bitcount(0x2DC1AC)) + prev(bitcount(0x2DC1AD)) + prev(bitcount(0x2DC1AE)) +
               prev(bitcount(0x2DC1AF)) + prev(bitcount(0x2DC1B0)) + prev(bitcount(0x2DC1B1)) + prev(bitcount(0x2DC1B2))
               + prev(bitcount(0x2DC1B3)) + prev(bitcount(0x2DC1B4)) + prev(bitcount(0x2DC1B5)) + prev(bit0(0x2DC1B6)) +
               prev(bit1(0x2DC1B6))) == 337
)

achievement(
    title = "I Can Do This All Day", points = 5,
    description = "Earn 20 wins in a row in Survival Mode",
    id = 195897, badge = "217857", published = "2/2/2022 6:12:03 PM", modified = "2/3/2022 5:32:32 AM",
    trigger = byte(0x2CAC68) == 4 && prev(dword(0x2CAF04)) == 19 && dword(0x2CAF04) == 20
)

achievement(
    title = "Maker Meeter-er", points = 10,
    description = "Earn 40 wins in a row in Survival Mode",
    id = 195898, badge = "217858", published = "2/2/2022 6:12:03 PM", modified = "2/3/2022 5:32:33 AM",
    trigger = byte(0x2CAC68) == 4 && prev(dword(0x2CAF04)) == 39 && dword(0x2CAF04) == 40
)

achievement(
    title = "I Am Death", points = 25,
    description = "Earn 60 wins in a row in Survival Mode",
    id = 195899, badge = "217859", published = "2/2/2022 6:12:03 PM", modified = "2/3/2022 5:32:33 AM",
    trigger = byte(0x2CAC68) == 4 && prev(dword(0x2CAF04)) == 59 && dword(0x2CAF04) == 60
)

achievement(
    title = "Survivor of Hathsin", points = 10,
    description = "Earn 20 wins in a row in Extra Survival Mode [Default Settings]",
    id = 195869, badge = "217860", published = "2/2/2022 5:07:25 AM", modified = "2/3/2022 12:49:52 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 5 && dword(0x2CAF04) == 20 && prev(dword(0x2CAF04)) == 19
)

achievement(
    title = "Lord of Scars", points = 25,
    description = "Earn 40 wins in a row in Extra Survival Mode [Default Settings]",
    id = 195870, badge = "217861", published = "2/2/2022 5:07:25 AM", modified = "2/3/2022 12:50:03 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 5 && dword(0x2CAF04) == 40 && prev(dword(0x2CAF04)) == 39
)

achievement(
    title = "Mist Lord", points = 50,
    description = "Earn 60 wins in a row in Extra Survival Mode [Default Settings]",
    id = 195871, badge = "217862", published = "2/2/2022 5:07:26 AM", modified = "2/3/2022 12:50:20 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) == 5 && dword(0x2CAF04) == 60 && prev(dword(0x2CAF04)) == 59
)

achievement(
    title = "Not-SlowCalibur", points = 10,
    description = "Complete Time Attack mode in under 4 minutes",
    id = 195895, badge = "217864", published = "2/2/2022 6:08:05 PM", modified = "2/3/2022 5:34:02 AM",
    trigger = never(dword(0x2CAC68) != 2) && never(word(0x2CACA0) >= 4) && once(dword(0x2C817C) == 19 && dword(0x2C8144)
               == 7 && prev(dword(0x2C1B00)) == 1 && dword(0x2C1B00) == 2)
)

achievement(
    title = "No Fighting!", points = 25,
    description = "Complete Time Attack mode with all Ring Outs",
    id = 195896, badge = "217865", published = "2/2/2022 6:08:06 PM", modified = "2/3/2022 5:34:02 AM",
    trigger = never(dword(0x2CAC68) != 2) && measured(tally(16, 
                  repeated(2, dword(0x2C8144) == 0 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3), 
                  repeated(2, dword(0x2C8144) == 1 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3), 
                  repeated(2, dword(0x2C8144) == 2 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3), 
                  repeated(2, dword(0x2C8144) == 3 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3), 
                  repeated(2, dword(0x2C8144) == 4 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3), 
                  repeated(2, dword(0x2C8144) == 5 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3), 
                  repeated(2, dword(0x2C8144) == 6 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3), 
                  repeated(2, dword(0x2C8144) == 7 && prev(dword(0x2CA1EC)) == 0 && dword(0x2CA1EC) == 3)
              ))
)

achievement(
    title = "And One More Thing...!", points = 5,
    description = "In Arcade mode, hit an opponent at least 7 times after they've already been KO'd",
    id = 195929, badge = "217899", published = "2/3/2022 4:08:33 AM", modified = "10/22/2022 1:45:21 AM",
    trigger = never(byte(0x2BFA58) != 0) && never(dword(0x2C1B00) == 0) && never(dword(0x2CA1EC) == 0) && 
              never(dword(0x2CAC68) != 1) && repeated(7, byte(0x2CA380) > prev(byte(0x2CA380)))
)

achievement(
    title = "Fully Loaded", points = 1,
    description = "Trigger Soul Charge for the first time during a match in arcade mode [>= Medium] [Any Character] [Default Settings]",
    id = 195925, badge = "217892", published = "2/3/2022 1:10:53 AM", modified = "2/3/2022 4:10:30 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) != 6 && byte(0x2CAC68) != 3 && byte(0x2CAC68) <= 8 &&
              ((byte(0x2BFA58) == 0 && dword(0x2C1B6C) == 7 && prev(dword(0x2C1B6C)) == 6) ||
               (byte(0x2BFA58) == 1 && dword(0x2CA24C) == 7 && prev(dword(0x2CA24C)) == 6))
)

achievement(
    title = "Early Bird", points = 1,
    description = "Trigger Spirit Charge for the first time during a match in arcade mode [>= Medium] [Any Character] [Default Settings]",
    id = 195926, badge = "217893", published = "2/3/2022 1:10:54 AM", modified = "2/3/2022 4:18:58 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              byte(0x2CAC68) != 6 && byte(0x2CAC68) != 3 && byte(0x2CAC68) <= 8 &&
              ((byte(0x2BFA58) == 0 && dword(0x2C1B6C) == 8 && prev(dword(0x2C1B6C)) == 6) ||
               (byte(0x2BFA58) == 1 && dword(0x2CA24C) == 8 && prev(dword(0x2CA24C)) == 6))
)

achievement(
    title = "Full Power Blow", points = 25,
    description = "Land 15 Soul Charged attacks in a single session in arcade mode [>= Medium] [Any Character] [Default Settings]",
    id = 195927, badge = "217895", published = "2/3/2022 1:10:54 AM", modified = "2/3/2022 4:47:00 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              unless(byte(0x2CAC68) != 1) &&
              ((repeated(15, byte(0x2BFA58) == 0 && dword(0x2C1B6C) == 7 && word(0x2CA27E) < prev(word(0x2CA27E)))) ||
               (repeated(15, byte(0x2BFA58) == 1 && dword(0x2CA24C) == 7 && word(0x2C1B9E) < prev(word(0x2C1B9E)))))
)

achievement(
    title = "Full Counter", points = 10,
    description = "Land 50 Spirit Charged attacks in a single session in arcade mode [>= Medium] [Any Character] [Default Settings]",
    id = 195928, badge = "217894", published = "2/3/2022 1:10:54 AM", modified = "2/3/2022 4:47:00 AM",
    trigger = byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && byte(0x2CAD60) == 0 && 
              unless(byte(0x2CAC68) != 1) &&
              ((repeated(50, byte(0x2BFA58) == 0 && dword(0x2C1B6C) == 8 && word(0x2CA27E) < prev(word(0x2CA27E)))) ||
               (repeated(50, byte(0x2BFA58) == 1 && dword(0x2CA24C) == 8 && word(0x2C1B9E) < prev(word(0x2C1B9E)))))
)

achievement(
    title = "Whipped Into Shape", points = 5,
    description = "Perform Summon Suffering as Ivy during a match [>= Medium] [Default Settings]",
    id = 195868, badge = "234309", published = "2/2/2022 5:07:25 AM", modified = "4/16/2022 3:00:40 PM",
    trigger = byte(0x2CAD50) >= 1 && byte(0x2CAD34) == 2 && byte(0x2CAD3C) == 40 && word(0x2CAD42) == 16288 && 
              byte(0x2CAD60) == 0 && byte(0x2CAC68) != 6 && byte(0x2CAC68) != 3 && byte(0x2CAC68) <= 8 &&
              ((byte(0x2BFA58) == 0 && word(0x2C1848) == 152 && prev(word(0x2C1848)) == 92) ||
               (byte(0x2BFA58) == 1 && word(0x2C9F28) == 152 && prev(word(0x2C9F28)) == 92))
)

leaderboard(
    id = 30538, title = "Survival",
    description = "Total Survival wins in a row",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1,
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30539, title = "Survival - Mitsurugi",
    description = "Total Survival wins in a row with [Mitsurugi]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 1) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 1)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30540, title = "Survival - Seung Mina",
    description = "Total Survival wins in a row with [Seung Mina]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 2) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 2)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30541, title = "Survival - Taki",
    description = "Total Survival wins in a row with [Taki]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 3) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 3)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30542, title = "Survival - Maxi",
    description = "Total Survival wins in a row with [Maxi]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 4) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 4)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30543, title = "Survival - Voldo",
    description = "Total Survival wins in a row with [Voldo]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 5) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 5)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30544, title = "Survival - Solphitia",
    description = "Total Survival wins in a row with [Mitsurugi]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 6) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 6)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30545, title = "Survival - Siegfried",
    description = "Total Survival wins in a row with [Siegfried]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 7) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 7)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30546, title = "Survival - Rock",
    description = "Total Survival wins in a row with [Rock]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 8) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 8)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30547, title = "Survival - Hwang",
    description = "Total Survival wins in a row with [Hwang]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 9) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 9)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30548, title = "Survival - Ivy",
    description = "Total Survival wins in a row with [Ivy]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 11) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 11)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30549, title = "Survival - Kilik",
    description = "Total Survival wins in a row with [Kilik]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 12) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 12)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30550, title = "Survival - Xianghua",
    description = "Total Survival wins in a row with [Xianghua]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 13) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 13)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30551, title = "Survival - Lizardman",
    description = "Total Survival wins in a row with [Lizardman]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 14) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 14)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30552, title = "Survival - Yoshimitsu",
    description = "Total Survival wins in a row with [Yoshimitsu]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 15) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 15)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30553, title = "Survival - Edge Master",
    description = "Total Survival wins in a row with [Edge Master]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 16) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 16)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30554, title = "Survival - Nightmare",
    description = "Total Survival wins in a row with [Nightmare]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 17) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 17)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30555, title = "Survival - Astaroth",
    description = "Total Survival wins in a row with [Astaroth]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 18) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 18)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30556, title = "Survival - Inferno",
    description = "Total Survival wins in a row with [Inferno]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 19) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 19)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30557, title = "Survival - Cervantes",
    description = "Total Survival wins in a row with [Cervantes]",
    start  = dword(0x2CAC68) == 4 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 20) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 20)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30558, title = "Extra Survival",
    description = "Total Survival wins in a row",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1,
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30559, title = "Extra Survival - Mitsurugi",
    description = "Total Survival wins in a row with [Mitsurugi]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 1) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 1)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30560, title = "Extra Survival - Seungmina",
    description = "Total Survival wins in a row with [Seungmina]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 2) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 2)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30561, title = "Extra Survival - Taki",
    description = "Total Survival wins in a row with [Taki]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 3) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 3)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30562, title = "Extra Survival - Maxi",
    description = "Total Survival wins in a row with [Maxi]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 4) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 4)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30563, title = "Extra Survival - Voldo",
    description = "Total Survival wins in a row with [Voldo]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 5) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 5)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30564, title = "Extra Survival - Solphitia",
    description = "Total Survival wins in a row with [Mitsurugi]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 6) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 6)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30565, title = "Extra Survival - Siegfried",
    description = "Total Survival wins in a row with [Siegfried]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 7) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 7)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30566, title = "Extra Survival - Rock",
    description = "Total Survival wins in a row with [Rock]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 8) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 8)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30567, title = "Extra Survival - Hwang",
    description = "Total Survival wins in a row with [Hwang]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 9) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 9)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30568, title = "Extra Survival - Ivy",
    description = "Total Survival wins in a row with [Ivy]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 11) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 11)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30569, title = "Extra Survival - Kilik",
    description = "Total Survival wins in a row with [Kilik]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 12) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 12)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30570, title = "Extra Survival - Xianghua",
    description = "Total Survival wins in a row with [Xianghua]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 13) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 13)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30571, title = "Extra Survival - Lizardman",
    description = "Total Survival wins in a row with [Lizardman]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 14) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 14)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30572, title = "Extra Survival - Yoshimitsu",
    description = "Total Survival wins in a row with [Yoshimitsu]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 15) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 15)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30573, title = "Extra Survival - Edge Master",
    description = "Total Survival wins in a row with [Edge Master]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 16) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 16)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30574, title = "Extra Survival - Nightmare",
    description = "Total Survival wins in a row with [Nightmare]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 17) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 17)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30575, title = "Extra Survival - Astaroth",
    description = "Total Survival wins in a row with [Astaroth]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 18) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 18)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30576, title = "Extra Survival - Inferno",
    description = "Total Survival wins in a row with [Inferno]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 19) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 19)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30577, title = "Extra Survival - Cervantes",
    description = "Total Survival wins in a row with [Cervantes]",
    start  = dword(0x2CAC68) == 5 && dword(0x2CAF04) == 1 &&
             ((byte(0x2BFA58) == 0 && byte(0x2BFA74) == 20) ||
              (byte(0x2BFA58) == 1 && dword(0x2C8154) == 20)),
    cancel = dword(0x2CAC68) == 0,
    submit = always_true() &&
             (((byte(0x2BFA58) == 1 && dword(0x2C1B00) == 1)) ||
              ((byte(0x2BFA58) == 0 && dword(0x2CA1E0) == 1))),
    value = dword(0x2CAF04),
    format = "VALUE"
)

leaderboard(
    id = 30578, title = "Time Attack - Mitsurugi",
    description = "",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 1,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30579, title = "Time Attack - Seung Mina",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 2,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30580, title = "Time Attack - Taki",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 3,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30581, title = "Time Attack - Maxi",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 4,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30582, title = "Time Attack - Voldo",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 5,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30583, title = "Time Attack - Sophitia",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 6,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30584, title = "Time Attack - Siegfried",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 7,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30585, title = "Time Attack - Rock",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 8,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30586, title = "Time Attack - Hwang",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 9,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30587, title = "Time Attack - Ivy",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 11,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30588, title = "Time Attack - Kilik",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 12,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30589, title = "Time Attack - Xianghua",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 13,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30590, title = "Time Attack - Lizardman",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 14,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30591, title = "Time Attack - Yoshimitsu",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 15,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30592, title = "Time Attack - Edge Master",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 16,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30593, title = "Time Attack - Nightmare",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 17,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30594, title = "Time Attack - Astaroth",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 18,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30595, title = "Time Attack - Inferno",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 19,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)

leaderboard(
    id = 30596, title = "Time Attack - Cervantes",
    description = "Complete as fast as you can",
    start  = byte(0x010110) == 0 && dword(0x2CAC68) == 2 && word(0x2CACA4) != 0 && byte(0x2BFA74) == 20,
    cancel = prev(dword(0x2CAC68)) == 2 && dword(0x2CAC68) != 2,
    submit = dword(0x2C1B00) == 2 && dword(0x2C8144) == 7 && dword(0x2C817C) != 0 && dword(0x2CA1EC) != 0,
    value = measured((word(0x2CACA4) + word(0x2CACA2) * 100 + word(0x2CACA0) * 3600 + 0)),
    format = "MILLISECS"
)
