site_name: tele dev log
site_url: https://example.com
nav:
    - Home: index.md
    - About: about.md
    - 'Set List':
      - The List: set-list.md
    - 'Sets':
      - 'Nintendo Entertainment System':
        - Deja Vu: sets/nes-dejavu.md
      - 'PlayStation':
        - Suikoden: sets/ps1-suikoden.md
      - 'PlayStation Portable':
        - Trails in the Sky FC: sets/psp-trailsintheskyfc.md
        - Trails in the Sky SC: sets/psp-trailsintheskysc.md
theme: material